framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            product: '%env(MESSENGER_TRANSPORT_DSN)%'
            attributes: '%env(ATTRIBUTE_TRANSPORT_DSN)%'
            category: '%env(CATEGORY_TRANSPORT_DSN)%'
            productredis: '%env(PRODUCT_REDIS_TRANSPORT_DSN)%'
            # failed: 'doctrine://default?queue_name=failed'
            # sync: 'sync://'

        routing:
            # Route your messages to the transports
            'App\DTO\ProductsDataTransferObject': product
            'App\DTO\AttributesDataTransferObject': attributes
            'App\DTO\CategoryDataTransferObject': category
            'App\DTO\RedisDataTransferObject': productredis

when@test:
    framework:
         messenger:
            transports:
                # replace with your transport name here (e.g., my_transport: 'in-memory://')
                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
                async: 'test://'
                async_priority_high: 'test://'
                product: 'test://'
                attributes: 'test://'
                productredis: 'test://'
                category: 'test://'
