controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
logout:
    path: /logout
controllers_product:
    resource:
        path: ../src/Component/Product/Communication/
        namespace: App\Component\Product\Communication
    type: attribute